//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvilaShellAppSample.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AvilaShellAppSample.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        public static string HomePagePhoneNumberHeader {
            get {
                return ResourceManager.GetString("HomePagePhoneNumberHeader", resourceCulture);
            }
        }
        
        public static string HomePageAvilaPhoneNumber {
            get {
                return ResourceManager.GetString("HomePageAvilaPhoneNumber", resourceCulture);
            }
        }
        
        public static string HomePageAddressHeader {
            get {
                return ResourceManager.GetString("HomePageAddressHeader", resourceCulture);
            }
        }
        
        public static string HomePageAvilaAddressName {
            get {
                return ResourceManager.GetString("HomePageAvilaAddressName", resourceCulture);
            }
        }
        
        public static string HomePageAvilaAddressStreet {
            get {
                return ResourceManager.GetString("HomePageAvilaAddressStreet", resourceCulture);
            }
        }
        
        public static string HomePageAvilaAddressZipCode {
            get {
                return ResourceManager.GetString("HomePageAvilaAddressZipCode", resourceCulture);
            }
        }
        
        public static string HomePageAvilaAddressCity {
            get {
                return ResourceManager.GetString("HomePageAvilaAddressCity", resourceCulture);
            }
        }
        
        public static string HomePageAvilaAddressCountry {
            get {
                return ResourceManager.GetString("HomePageAvilaAddressCountry", resourceCulture);
            }
        }
        
        public static string HomePageScheduleHeader {
            get {
                return ResourceManager.GetString("HomePageScheduleHeader", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleMonday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleMonday", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleTuesday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleTuesday", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleWednesday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleWednesday", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleThursday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleThursday", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleFriday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleFriday", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleSaturday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleSaturday", resourceCulture);
            }
        }
        
        public static string HomePageAvilaScheduleSunday {
            get {
                return ResourceManager.GetString("HomePageAvilaScheduleSunday", resourceCulture);
            }
        }
        
        public static string HomePageEmailHeader {
            get {
                return ResourceManager.GetString("HomePageEmailHeader", resourceCulture);
            }
        }
        
        public static string HomePageAvilaEmail {
            get {
                return ResourceManager.GetString("HomePageAvilaEmail", resourceCulture);
            }
        }
    }
}
